[package]
name = "dcf-framework"
version = "0.1.0"
edition = "2025"
license = "GPL-3.0"
description = "DCF Framework for Cross-Compatible Multiplayer Games on Nintendo DSi and Sony PSP"
repository = "https://github.com/ALH477/DCF-Handheld-Framework"
readme = "README.md"
authors = ["DeMoD LLC", "xAI (Grok 4 Heavy)"]
keywords = ["dcf", "streamdb", "multiplayer", "dsi", "psp"]
categories = ["embedded", "game-engines", "network-programming"]

[dependencies]
libnds = { git = "https://github.com/oxcabe/libnds-rs", optional = true }
psp = { git = "https://github.com/overdrivenpotato/rust-psp", optional = true }
heapless = "0.8"
lru = { version = "0.12", default-features = false }
crc = { version = "3.2", default-features = false }
byteorder = { version = "1.5", default-features = false }

[build-dependencies]
cc = "1.0"  # For linking platform-specific C libraries if needed (e.g., custom FFI builds)

[features]
dsi = ["libnds"]
psp = ["psp"]

[profile.release]
opt-level = "z"  # Smallest code size
lto = true  # Link-time optimization
codegen-units = 1  # Single unit for better opt
panic = "abort"  # No unwind for smaller code
strip = true  # Strip symbols

[profile.dev]
panic = "abort"  # For no_std
