[package]
name = "dcf-rust-sdk"
version = "5.0.1"
edition = "2021"
description = "Rust SDK for DeMoD Communication Framework (DCF)"
license = "GPL-3.0"

[dependencies]
tonic = "0.10"
prost = "0.12"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
parking_lot = "0.12"
byteorder = "1.4"
crc = "3.0"
lru = "0.8"
snappy = "0.3"
futures = "0.3"
memmap2 = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
rand = "0.8"
async-trait = "0.1"
config = "0.13"
toml = "0.8"
mdns-sd = "0.5" # For P2P peer discovery

[build-dependencies]
tonic-build = "0.10"
