[streamdb]
page_size = 4096
page_header_size = 32
max_db_size = 8000000000000
max_pages = 9223372036854775807
max_document_size = 268435456
page_cache_size = 2048
versions_to_keep = 2
use_mmap = true
use_compression = true

grpc_port = 50051
p2p_discovery = true
